version: 2
updates:
  # Backend Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: "develop"
    assignees:
      - "@me"
    commit-message:
      prefix: "backend"
      prefix-development: "deps"
    labels:
      - "dependencies"
      - "backend"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  # Frontend Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: "develop"
    assignees:
      - "@me"
    commit-message:
      prefix: "frontend"
      prefix-development: "deps"
    labels:
      - "dependencies"
      - "frontend"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    target-branch: "develop"
    commit-message:
      prefix: "docker"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    target-branch: "develop"
    commit-message:
      prefix: "docker"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    target-branch: "develop"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
