version: '3.8'

services:
  # PostgreSQL Database for development
  postgres-dev:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: oatie_ai_dev
      POSTGRES_USER: oatie_dev
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - oatie-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oatie_dev -d oatie_ai_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for development
  redis-dev:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    networks:
      - oatie-dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Backend API for development
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: backend-production
    environment:
      - DATABASE_URL=postgresql://oatie_dev:dev_password@postgres-dev:5432/oatie_ai_dev
      - REDIS_URL=redis://redis-dev:6379
      - SECRET_KEY=dev_secret_key_change_in_production
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - PROMETHEUS_ENABLED=true
      - BACKEND_CORS_ORIGINS=http://localhost:3000,http://localhost:8080
    depends_on:
      postgres-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
    ports:
      - "8001:8000"
    networks:
      - oatie-dev-network
    volumes:
      - ./backend:/app:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Frontend development server
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: frontend-production
    ports:
      - "8080:80"
    depends_on:
      backend-dev:
        condition: service_healthy
    networks:
      - oatie-dev-network
    environment:
      - REACT_APP_API_URL=http://localhost:8001/api/v1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  oatie-dev-network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local