# Prometheus Configuration for Oatie AI Performance Monitoring
# Enterprise monitoring stack configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'production'
    service: 'oatie-ai-reporting'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Scrape configurations
scrape_configs:
  # Oatie AI Application Metrics
  - job_name: 'oatie-ai-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  # Frontend Performance Metrics (via Node Exporter)
  - job_name: 'oatie-ai-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 15s

  # Database Performance Metrics
  - job_name: 'oracle-database'
    static_configs:
      - targets: ['database-exporter:9161']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis Performance Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # System Metrics (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Container Metrics (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Load Balancer Metrics (NGINX)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s

  # Performance Test Results
  - job_name: 'performance-tests'
    static_configs:
      - targets: ['performance-metrics:9090']
    scrape_interval: 60s
    honor_labels: true

  # Business Metrics
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/api/v1/metrics/business'
    scrape_interval: 30s

# Remote write configuration for long-term storage
remote_write:
  - url: "http://prometheus-remote-storage:9201/write"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

# Storage configuration
storage:
  tsdb:
    retention.time: 15d
    retention.size: 50GB
    wal-compression: true