name: Bug Report
description: Report a bug or issue with Oatie AI Reporting Platform
title: "[BUG] "
labels: ["type:bug", "priority:P2", "status:triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us investigate and resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Enter data '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Dashboard
        - Oracle Connection
        - Reports
        - Data Visualization
        - Authentication
        - API
        - Database
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (Application unusable)
        - High (Major functionality broken)
        - Medium (Feature partially broken)
        - Low (Minor issue or cosmetic)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      placeholder: |
        - OS: [e.g., Windows 10, macOS 12.0, Ubuntu 20.04]
        - Browser: [e.g., Chrome 100, Firefox 98, Safari 15]
        - Node.js version: [e.g., 18.14.0]
        - Oracle Database version: [e.g., 19c Enterprise Edition]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages/Logs
      description: Please paste any relevant error messages or logs
      placeholder: Paste error messages, stack traces, or console logs here...
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop screenshots here or paste image URLs...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you have done the following
      options:
        - label: I have searched for existing issues and this is not a duplicate
          required: true
        - label: I have provided a clear and detailed description of the issue
          required: true
        - label: I have included steps to reproduce the issue
          required: true
        - label: I have specified the environment details
          required: true