name: Release Management

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      changelog: ${{ steps.changelog.outputs.changelog }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi

    - name: Generate changelog
      id: changelog
      run: |
        # Generate changelog since last tag
        LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        if [ -n "$LAST_TAG" ]; then
          CHANGELOG=$(git log --pretty=format:"- %s" $LAST_TAG..HEAD)
        else
          CHANGELOG=$(git log --pretty=format:"- %s")
        fi
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

  build-and-test:
    runs-on: ubuntu-latest
    needs: prepare-release
    strategy:
      matrix:
        component: [backend, frontend]
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.component }}
        tags: |
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ matrix.component }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run security scan on image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.component }}:${{ needs.prepare-release.outputs.version }}
        format: 'sarif'
        output: 'trivy-${{ matrix.component }}.sarif'

    - name: Upload security scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-${{ matrix.component }}.sarif'

  create-release:
    runs-on: ubuntu-latest
    needs: [prepare-release, build-and-test]
    permissions:
      contents: write
      packages: write
    
    steps:
    - uses: actions/checkout@v4

    - name: Create Release Notes
      id: release-notes
      run: |
        cat > release-notes.md << EOF
        # Oatie ${{ needs.prepare-release.outputs.version }}
        
        ## 🚀 What's New
        
        This release includes the following changes:
        
        ${{ needs.prepare-release.outputs.changelog }}
        
        ## 📦 Docker Images
        
        - Backend: \`ghcr.io/${{ github.repository }}-backend:${{ needs.prepare-release.outputs.version }}\`
        - Frontend: \`ghcr.io/${{ github.repository }}-frontend:${{ needs.prepare-release.outputs.version }}\`
        
        ## 🔧 Installation
        
        \`\`\`bash
        # Using Docker Compose
        docker-compose pull
        docker-compose up -d
        
        # Or specific versions
        docker pull ghcr.io/${{ github.repository }}-backend:${{ needs.prepare-release.outputs.version }}
        docker pull ghcr.io/${{ github.repository }}-frontend:${{ needs.prepare-release.outputs.version }}
        \`\`\`
        
        ## 🧪 Testing
        
        All tests pass:
        - ✅ Backend: 17/17 tests
        - ✅ Frontend: Unit and integration tests
        - ✅ Security: Vulnerability scans clean
        - ✅ Performance: Benchmarks within targets
        
        ## 📖 Documentation
        
        See our [documentation](https://github.com/${{ github.repository }}/wiki) for full setup instructions.
        EOF

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ needs.prepare-release.outputs.version }}
        release_name: 'Oatie ${{ needs.prepare-release.outputs.version }}'
        body_path: release-notes.md
        draft: false
        prerelease: false

    - name: Package release artifacts
      run: |
        # Create deployment package
        mkdir -p release-artifacts
        
        # Copy essential files
        cp docker-compose.yml release-artifacts/
        cp README.md release-artifacts/
        cp -r infrastructure/ release-artifacts/ 2>/dev/null || true
        
        # Create deployment guide
        cat > release-artifacts/DEPLOYMENT.md << EOF
        # Deployment Guide for Oatie ${{ needs.prepare-release.outputs.version }}
        
        ## Quick Start
        
        1. Download this release package
        2. Run: \`docker-compose up -d\`
        3. Access the application at http://localhost:5174
        4. API available at http://localhost:8000
        
        ## Configuration
        
        Update environment variables in docker-compose.yml as needed.
        
        ## Database Setup
        
        The application will automatically apply database migrations on startup.
        EOF
        
        # Create archive
        tar -czf oatie-${{ needs.prepare-release.outputs.version }}.tar.gz -C release-artifacts .

    - name: Upload release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: oatie-release-${{ needs.prepare-release.outputs.version }}
        path: oatie-${{ needs.prepare-release.outputs.version }}.tar.gz

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [prepare-release, create-release]
    environment: staging
    
    steps:
    - name: Deploy to staging
      run: |
        echo "🚀 Deploying Oatie ${{ needs.prepare-release.outputs.version }} to staging..."
        # Add your staging deployment logic here
        # This could include:
        # - Updating Kubernetes manifests
        # - Running database migrations
        # - Health checks
        echo "✅ Staging deployment completed!"

  deploy-production:
    runs-on: ubuntu-latest
    needs: [prepare-release, create-release, deploy-staging]
    environment: production
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    
    steps:
    - name: Deploy to production
      run: |
        echo "🚀 Deploying Oatie ${{ needs.prepare-release.outputs.version }} to production..."
        # Add your production deployment logic here
        echo "✅ Production deployment completed!"

    - name: Notify stakeholders
      run: |
        echo "📧 Notifying stakeholders of release ${{ needs.prepare-release.outputs.version }}"
        # Add notification logic (Slack, email, etc.)
